### ISSUE TITLE
Deregister the default safe_html transform

### ISSUE THREAD

**Issue by tisto** [collective/experimental.safe_html_transform#2]

**Comment by tisto** [comment]
Find the method to unregister a transform. Something like:

transforms = getToolByName(portal, 'portal_transforms')
transforms.remove_transform(...)

I'm not sure about the method name to remove a transform. Add a debugger (pdb) statement and check which methods portal_transforms provide. Best way to do this is to write a test for the unregister in tests/test_setup.py.

**Comment by vincentfretin** [comment]
@tisto Did you see plone.outputfilters.setuphandlers.unregister_transform?
Products.TinyMCE.setuphandlers.uninstall_mimetype_and_transforms uses that.

**Comment by tisto** [comment]
@vincentfretin No. Thanks for the hint!
@prakharjoshi You bascially have everything you need here: https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/setuphandlers.py#L30

**Comment by prakharjoshi** [comment]
@tisto  Added the unregisteration of safe_html of PortalTransform .

**Comment by prakharjoshi** [comment]
@tisto  Check the last commit
