### ISSUE TITLE
Add new "safe_html_experimental" transform.

### ISSUE THREAD

**Issue by tisto** [collective/experimental.safe_html_transform#21]
Add a new "safe_html_experimental" transform to the package. Copy and amend code from:

https://github.com/plone/plone.intelligenttext

The idea behind this is to do smaller steps and solve the most important problems first. Once we have this additional transform, @prakharjoshi can start to work on the actual implementation (lxml, etc.) and on the tests. We can postpone other issues such as overriding safe_html which might be complicated.

**Comment by tisto** [comment]
Todo (from Skype talk):

1) Register a "experimental_safe_html"
2) Make sure that this new "experimental_save_html" is actually used (either by checking manually or writing a test for it)
3) Try to register the transform under the "safe_html" name and try to unregister the old one (make sure that this actually works)

**Comment by lentinj** [comment]
Notes on registration. Unfortunately, the registration part of intelligenttext isn't actually separate to PortalTransforms, like we suggested it might. However, here's a self-contained example:

https://github.com/tutor-web/tutorweb.content/blob/master/tutorweb/content/setuphandlers.py#L22

`availableTransforms` just lists all the modules available with transforms in. Don't worry about that bit, you only have one.

Here's another example, which makes it clearer what the arguments are to `manage_addTransform`:

https://github.com/Connexions/rhaptos.cnxmltransforms/blob/master/rhaptos/cnxmltransforms/setuphandlers.py

Finally, some notes on setuphandlers.py --- you'll want to read this:

http://docs.plone.org/develop/addons/components/genericsetup.html#custom-installer-code-setuphandlers-py

**Comment by prakharjoshi** [comment]
@tisto  @lentinj  I think #28  Will do install the transform. For testing the transform I am creating a new issue :)
