### ISSUE TITLE
Create HTML filter control panel and read configuration from there

### ISSUE THREAD

**Issue by tisto** [collective/experimental.safe_html_transform#4]
https://github.com/plone/Products.CMFPlone/commit/ac98b0ea4ae27f4b74f4d3c5cf100b54f8acbfb7
https://gist.github.com/tisto/4ef1f6c7b445faf6ad73

**Comment by tisto** [comment]
@prakharjoshi please create a new pull request and branch named "fix-4" that just contains the control panel, nothing more. Make sure all tests pass and travis is happy. We have to go step by step.

https://github.com/collective/experimental.safe_html_transform/pull/1 is a wild mix of different things that make it really hard to review.

**Comment by tisto** [comment]
@prakharjoshi I merged the control panel pull request. Though, the Zope instance did not start at all. I had to amend the permissions to make the Zope instance start.

Please write a few tests for the control panel like those:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_site.py

and fix the remaining issues.

The control panel currently can not be accessed because the URLs do not match. If you do not write tests, you have to at least check manually that the code works (start Zope instance, add Plone instance, install add-on product, go to the control panel and change some settings).

**Comment by prakharjoshi** [comment]
@lentinj @tisto When I tried to start the plone instance to install our add-on.. The instance is not working showing an error "KeyError('Interface `Products.CMFPlone.interfaces.controlpanel.ISiteSchema` defines a field `site_logo`, for which there is no record.',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: Interface `Products.CMFPlone.interfaces.controlpanel.ISiteSchema` defines a field `site_logo`, for which there is no record.)" on "bin/instance fg"

**Comment by lentinj** [comment]
@prakharjoshi Are you working on a clean checkout of collective:master?

**Comment by prakharjoshi** [comment]
@lentinj I am currently on branch 5.0. Also to check by adding our add-on I have to run plone so I should work with pone4 or should I install plone5 and create a website and add my controlpanel there as I need to check for the controlpanel (it is showing error as told above ).

**Comment by tisto** [comment]
@prakharjoshi that comes from Plone 5. We are working with Plone 4, right? Just remove the Plone instance and create a new one.

**Comment by tisto** [comment]
@prakharjoshi Plone 5.0 branch? You should really work on Plone 4.3.

**Comment by prakharjoshi** [comment]
@tisto  Okay Sure Will remove that will clone again with 4.3, Okay ?

**Comment by lentinj** [comment]
@prakharjoshi so is your site here something created with `buildout.coredev`? Yes, you should be using the 4.3 branch, and clear out the old site before you run buildout.

**Comment by prakharjoshi** [comment]
@lentinj Okay Now I created a new instance using plone-4.3.4 unified installer, earlier I was cloning the core branch and trying to run that in fg mode. Now I created an instance and started plone site in fg mode and tried to change buildout.cfg by adding "experiemental.safe_html_transfrom" into the eggs and did bin/buildout, the logs shows this message http://pastie.org/10248836 . So first thing we have to make experiemental.safe_html_transform to be added as an add-on on plone site, right ?
Any guidance for that issue ?

**Comment by lentinj** [comment]
Since there are no releases to `experimental.safe_html_transform`, buildout can't find any. To get around this, you need to use mr.developer to clone from Github. This you must have done before, regardless of whether you were using buildout.coredev or the unified installer. Do you still have the line you added in the `[sources]` section before?

**Comment by tisto** [comment]
The package iteself comes with a working buildout configuration. Just do:

```
git clone git@github.com:collective/experimental.safe_html_transform.git
cd experimental.safe_html_transform
python2.7 bootstrap-buildout.py
bin/buildout
bin/instance fg
```

**Comment by prakharjoshi** [comment]
@tisto  I guess there is no bootstrap.py file in our add-on, so "python2.7 bootstrap.py" will show error as "python2.7: can't open file 'bootstrap.py': [Errno 2] No such file or directory". And one more thing we need to add this add-on in the site and this way we will run site from our add-on, doesn't these things different ?

**Comment by tisto** [comment]
Sorry, it is bootstrap-buildout.py. I amended my example above. I don't understand your question though.

**Comment by lentinj** [comment]
@prakharjoshi ordinarily yes. You would make a site using buildout then include the add-on in your buildout.cfg. However using the buildout.cfg in the add-on (which includes both Plone and our add-on) results in the same thing.

**Comment by prakharjoshi** [comment]
Okay. This way there will be no need to create a new instance and then add our add-on.

**Comment by prakharjoshi** [comment]
There is conflict error for setuptools "VersionConflict: (setuptools 17.1.1 (/home/prakhar/experiment/experimental.safe_html_transform/eggs/setuptools-17.1.1-py2.7.egg), Requirement.parse('setuptools==8.3'))". We pinned setuptool to 8.3 to make travis happy and now here it is showing conflict :/  when I was doing sudo bin/buildout

**Comment by prakharjoshi** [comment]
@tisto  I pushed the commit now zope instance is running perfectly but there is nothing shown on the page, it is showing that this page doesn't seems to exists... I used the same url in the profile/default/controlpanel.zml as shown in the browser.. So is there something else to be done to render the control panel filter on our site ?

**Comment by prakharjoshi** [comment]
@lentinj  @tisto  I think this issue is solve in the pull request #25 . So please have a look at this and if its okay then I think we can close that issue too ?
